# Generated by Django 2.0.2 on 2018-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=32)),
                ('altusername', models.CharField(max_length=32)),
                ('cwd', models.CharField(max_length=255)),
                ('oldpwd', models.CharField(max_length=255)),
                ('command', models.TextField()),
            ],
        ),
    ]
