// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history.proto

/*
Package history is a generated protocol buffer package.

It is generated from these files:
	history.proto

It has these top-level messages:
	Command
*/
package history

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Hostname    string   `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Timestamp   int64    `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Username    string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Altusername string   `protobuf:"bytes,4,opt,name=altusername" json:"altusername,omitempty"`
	Cwd         string   `protobuf:"bytes,5,opt,name=cwd" json:"cwd,omitempty"`
	Oldpwd      string   `protobuf:"bytes,6,opt,name=oldpwd" json:"oldpwd,omitempty"`
	Command     []string `protobuf:"bytes,7,rep,name=command" json:"command,omitempty"`
	Exitcode    int64    `protobuf:"varint,8,opt,name=exitcode" json:"exitcode,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Command) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Command) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Command) GetAltusername() string {
	if m != nil {
		return m.Altusername
	}
	return ""
}

func (m *Command) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *Command) GetOldpwd() string {
	if m != nil {
		return m.Oldpwd
	}
	return ""
}

func (m *Command) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Command) GetExitcode() int64 {
	if m != nil {
		return m.Exitcode
	}
	return 0
}

func init() {
	proto.RegisterType((*Command)(nil), "history.Command")
}

func init() { proto.RegisterFile("history.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0xca, 0xc2, 0x30,
	0x10, 0xc5, 0xc9, 0x97, 0xcf, 0xa6, 0x1d, 0x11, 0x24, 0x0b, 0x09, 0xe2, 0x22, 0xb8, 0xea, 0xca,
	0x8d, 0x47, 0xf0, 0x06, 0xbd, 0x41, 0x6c, 0x02, 0x2d, 0x34, 0x9d, 0xd2, 0x8c, 0x54, 0x8f, 0xeb,
	0x4d, 0xa4, 0xe9, 0x1f, 0xdd, 0xcd, 0xef, 0x3d, 0x1e, 0xfc, 0x06, 0x76, 0x55, 0x1d, 0x08, 0xfb,
	0xd7, 0xa5, 0xeb, 0x91, 0x50, 0x8a, 0x19, 0xcf, 0x6f, 0x06, 0xe2, 0x86, 0xde, 0x9b, 0xd6, 0xca,
	0x23, 0xa4, 0x15, 0x06, 0x6a, 0x8d, 0x77, 0x8a, 0x69, 0x96, 0x67, 0xc5, 0xca, 0xf2, 0x04, 0x19,
	0xd5, 0xde, 0x05, 0x32, 0xbe, 0x53, 0x7f, 0x9a, 0xe5, 0xbc, 0xf8, 0x06, 0xe3, 0xf2, 0x11, 0x5c,
	0x1f, 0x97, 0x7c, 0x5a, 0x2e, 0x2c, 0x35, 0x6c, 0x4d, 0x43, 0x6b, 0xfd, 0x1f, 0xeb, 0xdf, 0x48,
	0xee, 0x81, 0x97, 0x83, 0x55, 0x9b, 0xd8, 0x8c, 0xa7, 0x3c, 0x40, 0x82, 0x8d, 0xed, 0x06, 0xab,
	0x92, 0x18, 0xce, 0x24, 0x15, 0x88, 0x72, 0x92, 0x55, 0x42, 0xf3, 0x3c, 0x2b, 0x16, 0x1c, 0x0d,
	0xdc, 0xb3, 0xa6, 0x12, 0xad, 0x53, 0x69, 0xd4, 0x5b, 0xf9, 0x9e, 0xc4, 0x9f, 0xaf, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0x48, 0x8e, 0x18, 0x04, 0x01, 0x00, 0x00,
}
